const constants = {
  SET_KEYWORDS: "CHANGE_KEYWORDS",
  ADD_TWEET: "ADD_TWEET",
  CLEAR_RESERVOIR: "CLEAR_RESERVOIR",
  SET_RESERVOIR_SIZE: "SET_RESERVOIR_SIZE",
  SET_AVG_LENGTH: "SET_AVG_LENGTH",
  SET_TOP_HASHTAGS: "SET_TOP_HASHTAGS",
  FETCH_TWEETS: "FETCH_TWEETS",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants
